insert into profile (id,
                     created_at,
                     updated_at,
                     email,
                     full_name,
                     password,
                     phone_number,
                     profile_type)
VALUES ('6f23c145-ad59-4b4d-ab21-c8140216c74d',
        NOW(),
        NOW(),
        'filimon.mark@gmail.com',
        'Márk Filimon',
        '$2b$12$SV.C1MSsU4yE/WzuCZxq3uabhgXJRKYqxt72PkeNbc3UcEKSAIIHG',
        '+36703334444',
        'ADMIN')