server:
  port: 8080

spring:
  application:
    name: "Restaurant Manager Backend"
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_manager
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1h in millisecond
